2019-11-07T10:18:18|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\hardware.py", line 219, in enable_connection
    raise err
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\hardware.py", line 212, in enable_connection
    self.disconnect()
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\hardware.py", line 198, in disconnect
    raise NotImplementedError()
NotImplementedError

2019-11-07T10:18:22|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\hardware.py", line 204, in enable_connection
    self.connect()
  File "C:\Users\Admin\Desktop\MFCS_python_old\PumpHardware.py", line 39, in connect
    self.read_pressure_1.hardware_read_func = self.MFCS.read_preessure_channel(1)
  File "C:\Users\Admin\Desktop\MFCS_python_old\PumpDevice.py", line 47, in read_preessure_channel
    C_error = lib_mfcs.mfcs_read_chan(c_ulonglong(mfcsHandle),ch,byref(pressure_read), byref(timeStamp))
TypeError: an integer is required (got type c_ulonglong)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\hardware.py", line 219, in enable_connection
    raise err
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\hardware.py", line 212, in enable_connection
    self.disconnect()
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\hardware.py", line 198, in disconnect
    raise NotImplementedError()
NotImplementedError

2019-11-07T10:18:22|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\hardware.py", line 208, in enable_connection
    raise err
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\hardware.py", line 204, in enable_connection
    self.connect()
  File "C:\Users\Admin\Desktop\MFCS_python_old\PumpHardware.py", line 39, in connect
    self.read_pressure_1.hardware_read_func = self.MFCS.read_preessure_channel(1)
  File "C:\Users\Admin\Desktop\MFCS_python_old\PumpDevice.py", line 47, in read_preessure_channel
    C_error = lib_mfcs.mfcs_read_chan(c_ulonglong(mfcsHandle),ch,byref(pressure_read), byref(timeStamp))
TypeError: an integer is required (got type c_ulonglong)

2019-11-07T10:18:23|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\hardware.py", line 204, in enable_connection
    self.connect()
  File "C:\Users\Admin\Desktop\MFCS_python_old\PumpHardware.py", line 39, in connect
    self.read_pressure_1.hardware_read_func = self.MFCS.read_preessure_channel(1)
  File "C:\Users\Admin\Desktop\MFCS_python_old\PumpDevice.py", line 47, in read_preessure_channel
    C_error = lib_mfcs.mfcs_read_chan(c_ulonglong(mfcsHandle),ch,byref(pressure_read), byref(timeStamp))
TypeError: an integer is required (got type c_ulonglong)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\hardware.py", line 219, in enable_connection
    raise err
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\hardware.py", line 212, in enable_connection
    self.disconnect()
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\hardware.py", line 198, in disconnect
    raise NotImplementedError()
NotImplementedError

2019-11-07T10:18:23|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\hardware.py", line 208, in enable_connection
    raise err
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\hardware.py", line 204, in enable_connection
    self.connect()
  File "C:\Users\Admin\Desktop\MFCS_python_old\PumpHardware.py", line 39, in connect
    self.read_pressure_1.hardware_read_func = self.MFCS.read_preessure_channel(1)
  File "C:\Users\Admin\Desktop\MFCS_python_old\PumpDevice.py", line 47, in read_preessure_channel
    C_error = lib_mfcs.mfcs_read_chan(c_ulonglong(mfcsHandle),ch,byref(pressure_read), byref(timeStamp))
TypeError: an integer is required (got type c_ulonglong)

2019-11-07T10:18:24|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\hardware.py", line 204, in enable_connection
    self.connect()
  File "C:\Users\Admin\Desktop\MFCS_python_old\PumpHardware.py", line 39, in connect
    self.read_pressure_1.hardware_read_func = self.MFCS.read_preessure_channel(1)
  File "C:\Users\Admin\Desktop\MFCS_python_old\PumpDevice.py", line 47, in read_preessure_channel
    C_error = lib_mfcs.mfcs_read_chan(c_ulonglong(mfcsHandle),ch,byref(pressure_read), byref(timeStamp))
TypeError: an integer is required (got type c_ulonglong)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\hardware.py", line 219, in enable_connection
    raise err
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\hardware.py", line 212, in enable_connection
    self.disconnect()
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\hardware.py", line 198, in disconnect
    raise NotImplementedError()
NotImplementedError

2019-11-07T10:18:24|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\hardware.py", line 208, in enable_connection
    raise err
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\hardware.py", line 204, in enable_connection
    self.connect()
  File "C:\Users\Admin\Desktop\MFCS_python_old\PumpHardware.py", line 39, in connect
    self.read_pressure_1.hardware_read_func = self.MFCS.read_preessure_channel(1)
  File "C:\Users\Admin\Desktop\MFCS_python_old\PumpDevice.py", line 47, in read_preessure_channel
    C_error = lib_mfcs.mfcs_read_chan(c_ulonglong(mfcsHandle),ch,byref(pressure_read), byref(timeStamp))
TypeError: an integer is required (got type c_ulonglong)

2019-11-07T10:18:26|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\hardware.py", line 204, in enable_connection
    self.connect()
  File "C:\Users\Admin\Desktop\MFCS_python_old\PumpHardware.py", line 39, in connect
    self.read_pressure_1.hardware_read_func = self.MFCS.read_preessure_channel(1)
  File "C:\Users\Admin\Desktop\MFCS_python_old\PumpDevice.py", line 47, in read_preessure_channel
    C_error = lib_mfcs.mfcs_read_chan(c_ulonglong(mfcsHandle),ch,byref(pressure_read), byref(timeStamp))
TypeError: an integer is required (got type c_ulonglong)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\hardware.py", line 219, in enable_connection
    raise err
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\hardware.py", line 212, in enable_connection
    self.disconnect()
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\hardware.py", line 198, in disconnect
    raise NotImplementedError()
NotImplementedError

2019-11-07T10:18:26|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\hardware.py", line 208, in enable_connection
    raise err
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\hardware.py", line 204, in enable_connection
    self.connect()
  File "C:\Users\Admin\Desktop\MFCS_python_old\PumpHardware.py", line 39, in connect
    self.read_pressure_1.hardware_read_func = self.MFCS.read_preessure_channel(1)
  File "C:\Users\Admin\Desktop\MFCS_python_old\PumpDevice.py", line 47, in read_preessure_channel
    C_error = lib_mfcs.mfcs_read_chan(c_ulonglong(mfcsHandle),ch,byref(pressure_read), byref(timeStamp))
TypeError: an integer is required (got type c_ulonglong)

