2019-11-07T10:01:46|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\hardware.py", line 219, in enable_connection
    raise err
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\hardware.py", line 212, in enable_connection
    self.disconnect()
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\hardware.py", line 198, in disconnect
    raise NotImplementedError()
NotImplementedError

2019-11-07T10:02:03|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\hardware.py", line 204, in enable_connection
    self.connect()
  File "C:\Users\Admin\Desktop\MFCS_python_old\PumpHardware.py", line 37, in connect
    self.readOnlyWhenOpt()
AttributeError: 'MFCSHardware' object has no attribute 'readOnlyWhenOpt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\hardware.py", line 219, in enable_connection
    raise err
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\hardware.py", line 212, in enable_connection
    self.disconnect()
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\hardware.py", line 198, in disconnect
    raise NotImplementedError()
NotImplementedError

2019-11-07T10:02:03|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\hardware.py", line 208, in enable_connection
    raise err
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\hardware.py", line 204, in enable_connection
    self.connect()
  File "C:\Users\Admin\Desktop\MFCS_python_old\PumpHardware.py", line 37, in connect
    self.readOnlyWhenOpt()
AttributeError: 'MFCSHardware' object has no attribute 'readOnlyWhenOpt'

2019-11-07T10:02:05|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\hardware.py", line 204, in enable_connection
    self.connect()
  File "C:\Users\Admin\Desktop\MFCS_python_old\PumpHardware.py", line 37, in connect
    self.readOnlyWhenOpt()
AttributeError: 'MFCSHardware' object has no attribute 'readOnlyWhenOpt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\hardware.py", line 219, in enable_connection
    raise err
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\hardware.py", line 212, in enable_connection
    self.disconnect()
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\hardware.py", line 198, in disconnect
    raise NotImplementedError()
NotImplementedError

2019-11-07T10:02:05|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\hardware.py", line 208, in enable_connection
    raise err
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\hardware.py", line 204, in enable_connection
    self.connect()
  File "C:\Users\Admin\Desktop\MFCS_python_old\PumpHardware.py", line 37, in connect
    self.readOnlyWhenOpt()
AttributeError: 'MFCSHardware' object has no attribute 'readOnlyWhenOpt'

2019-11-07T10:02:16|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\hardware.py", line 208, in enable_connection
    raise err
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\hardware.py", line 204, in enable_connection
    self.connect()
  File "C:\Users\Admin\Desktop\MFCS_python_old\CameraHardware.py", line 115, in connect
    binning = self.binning.val, hardware = self) #maybe with more cameras we have to change
  File "C:\Users\Admin\Desktop\MFCS_python_old\CameraDevice.py", line 336, in __init__
    raise DCAMException("DCAM initialization failed with error code " + str(error_code))
CameraDevice.DCAMException: DCAM initialization failed with error code -2147483130

