2019-11-11T15:00:12|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\hardware.py", line 208, in enable_connection
    raise err
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\hardware.py", line 204, in enable_connection
    self.connect()
  File "C:\Users\Admin\Desktop\MFCS_python_old\PumpHardware.py", line 42, in connect
    self.set_pressure_2.hardware_set_func = self.MFCS.set_pressure_channel()
TypeError: set_pressure_channel() missing 2 required positional arguments: 'P' and 'ch'

2019-11-11T15:00:20|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\hardware.py", line 208, in enable_connection
    raise err
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\hardware.py", line 204, in enable_connection
    self.connect()
  File "C:\Users\Admin\Desktop\MFCS_python_old\PumpHardware.py", line 42, in connect
    self.set_pressure_2.hardware_set_func = self.MFCS.set_pressure_channel()
TypeError: set_pressure_channel() missing 2 required positional arguments: 'P' and 'ch'

